### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by LReiz** [LReiz/BB-The-Birthday-Bot#1]
- [ ] Postar no Feed do Face
     - [ ] Postar mensagem
     - [ ] Postar imagem
- [ ] Pegar a data de aniversário
- [ ] Salvar as pessoas que quero parabenizar
     - [ ] Salvar nome no bd
     - [ ] Salvar adjetivos da pessoa no bd (substantivos na verdade)
- [ ] Hospedar o robô
